version: '2.4'

services:
  base:
    build:
      context: .
    volumes:
      - .:/app
    tty: true
    environment:
      - PYTHONPATH=.

  web:
    extends:
      file: docker-compose.yml
      service: base
    ports:
      - "8080:80"
    tty: true
    environment:
      - APP_ENV=production
      - MARKET_VALUE_HOST_URL=https://au.finance.dummy.com

  dev:
    extends:
      file: docker-compose.yml
      service: base
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development
      - MARKET_VALUE_HOST_URL=https://au.finance.dummy.com
    command: bash

  test:
    extends:
      file: docker-compose.yml
      service: base
    environment:
      - APP_ENV=test
    command: pipenv run python -m pytest
