version: '2.4'

services:
  base:
    build:
      context: .
    volumes:
      - .:/app

  web:
    extends:
      file: docker-compose.yml
      service: base
    ports:
      - "8080:80"
    tty: true
    environment:
      - APP_ENV=production

  dev:
    extends:
      file: docker-compose.yml
      service: base
    ports:
      - "8080:80"
    tty: true
    environment:
      - APP_ENV=development
      - MARKET_VALUE_HOST_URL=https://dummy-finance-site.com
    command: bash

  test:
    extends:
      file: docker-compose.yml
      service: base
    tty: true
    environment:
      - APP_ENV=test
    command: pipenv run python -m pytest
